### ISSUE TITLE
1125899906842620 bytes gives the result of 1024 TB because of rounding

### ISSUE THREAD

**Issue by ulitiy** [avoidwork/filesize.js#103]
I see the only way of solving it – very inelegant corner case management.
```
        let res = parseFloat((bytes / (1024 ** pow)).toFixed(precision));
        if (res === 1024) {
            res = 1;
            pow++;
        }
```

**Comment by avoidwork** [comment]
Thanks for reporting this

**Comment by zypA13510** [comment]
For those who are trying to make sense of this change:

1PB != 112589990684262**0** bytes, 1PB == 112589990684262**4** bytes, yes.
But filesize is expected to round up the result, e.g. filesize(104857**4**) == '1 MB' although 1024*1024 == 104857**6**

Hope this helps those who look for changelog like me.

**Comment by avoidwork** [comment]
I hope you would understand the issue and the fix based on the details provided, and the single commit to address the issue. A changelog won't help you reason why something is modified, it's just a subset of the commit log.

**Comment by avoidwork** [comment]
https://en.wikipedia.org/wiki/Changelog  <--- seriously stop being so entitled with the notion of the changelog already, and either land it or stfu.

**Comment by zypA13510** [comment]
Without a changelog, the only way to determine if an upgrade is "safe" or not is to look at the commit log, which I was doing. And clearly I failed to understand this change at first look.

I'm not arguing with you whether providing a changelog is a good thing or not, I'm merely giving people (who look for the details of an update, people like me) a better understanding of this issue and that's it, what's so wrong about that?

Btw, providing a changelog is not that difficult, you may want to look into [conventional commits](https://www.conventionalcommits.org/) and [semantic release](https://github.com/semantic-release/semantic-release)

**Comment by jennifer-shehane** [comment]
Reading through every commit for every package that is a dependency of a project is not sustainable. I would argue that a changelog is a very good thing. I too came looking for changes and am reading entire threads of the project to see what changed, which is not ideal. @zypA13510 Thanks for your comment - it makes the issue and commit much clearer.
