### ISSUE TITLE
Certificate for CDN is invalid

### ISSUE THREAD

**Issue by daffodilistic** [avoidwork/filesize.js#108]
Hello,

Just want to report that the SSL cert for the URL https://cdn.filesizejs.com/filesize.min.js is invalid.
![Screenshot 2019-10-24 at 10 35 35 AM](https://user-images.githubusercontent.com/2077533/67448590-0a294380-f64a-11e9-9c30-f56b6ed4ed96.png)

**Comment by avoidwork** [comment]
fixed
