### ISSUE TITLE
[IE11] Arrow functions included in build output causing breakage

### ISSUE THREAD

**Issue by mattvperry** [avoidwork/filesize.js#109]
The definition of the `filesize.partial` function is using arrow functions in the final build output file. Arrow functions are an ES6 feature and shouldn't be included in downlevel build output. This is causing breakage for IE11 and any other browser which does not yet have ES6 support. 

Workarounds include running babel on this file in your webpack config but thats not always an option

**Comment by avoidwork** [comment]
You don't have to run 5.x if you need that output.
