### ISSUE TITLE
what are the breaking changes?

### ISSUE THREAD

**Issue by dylang** [avoidwork/filesize.js#110]
Hi, I really appreciate your work in this module, and I understand the pain of creating release notes, but I'm at a loss trying to figure out the breaking changes from 4.x to 6.x in the changelog.

Github will let you add notes to the Releases tab. Just one line like "Breaking change: Not supporting node 6" would be helpful.

Thanks, and thanks again for your hard work on this!

**Comment by avoidwork** [comment]
5 was the breaking change, and apparently i messed up the types file in the revert. the only way to undo a breaking change that isn't desirable is revert & rolling major version.
