### ISSUE TITLE
Version 6 filesize.d.ts is empty & not declared in package.json

### ISSUE THREAD

**Issue by manferlo81** [avoidwork/filesize.js#111]
As of version 6.0.0 I noticed your filesize.d.ts file is empty. I noticed because is braking my ci test. I checked version 5.0.3 and the types are still there.

**Comment by manferlo81** [comment]
your `"types"` field in `package.json` was removed on [3909b04d72b7a8129d94a03612898feedf4d39b3](https://github.com/avoidwork/filesize.js/commit/3909b04d72b7a8129d94a03612898feedf4d39b3#diff-b9cfc7f2cdf78a7f4b91a753d10865a2) that's another reason your types are not working.

**Comment by marcneander** [comment]
Please fix this :)
