### ISSUE TITLE
feat: add fullform to output object mode

### ISSUE THREAD

**Issue by carlos22** [avoidwork/filesize.js#118]
A good UI uses `<abbr>` for the units with the full name as title. This is very hard to to with this lib. One would need to call it twice to the both, the short and long version of the `symbol`. In the `output: 'object'` mode it should be easy to add a `unit` prop with the fullform of the symbol?!

**Comment by avoidwork** [comment]
I'll add `unit` but it'll be the shortform, because `symbol` behavior can't change; it also works better for looking up the different specs imo.
