### ISSUE TITLE
[TypeScript] Return type reported to be incorrect when changing output type from the default

### ISSUE THREAD

**Issue by alpha-tango-kilo** [avoidwork/filesize.js#126]
Using TypeScript, I'm told that the following will return a string, which isn't correct:

```ts
fileSize(123123, { output: "object" });
```

What I expect to be able to do:

```ts
let { value, symbol, exponent } = fileSize(123123, { output: "object" });
```

Current workaround:

```ts
let { value, symbol, exponent } = fileSize(123123], { output: "object" }) as unknown as { value: number, symbol: string, exponent: number };
```

For clarity, it is actually an object that gets returned, just the type declarations are telling me I'm going to get a string

**Comment by alpha-tango-kilo** [comment]
Upon further usage, it seems the same seems to apply for all the different output options - they all say they're going to return string

**Comment by avoidwork** [comment]
File was lifted from https://github.com/DefinitelyTyped/DefinitelyTyped; I didn't write it. Feel free to open a PR with fix or updated from that repo.

**Comment by bhavya32** [comment]
@avoidwork do you know even whatsapp web uses your code?

**Comment by avoidwork** [comment]
@bhavya32 cool; i didn't.
