### ISSUE TITLE
[Typescript] Typing file out of date

### ISSUE THREAD

**Issue by willsteinmetz** [avoidwork/filesize.js#139]
It appears that the typing file is out of date. In the code in the repo, it references version 6.0.1.

When I try to import the library into a Typescript file, the transpiler gives me an error that filesize doesn't have a default export (which actually does match the typing file in the package).

So far I haven't figured out a work around and I think it may just be that the typing file needs to be updated.

**Comment by avoidwork** [comment]
yup, feel free to make a PR; otherwise this bug will sit forever.

**Comment by avoidwork** [comment]
afaik the typescript file has never been correct. the original authors of it only used 1 output type when 3 existed.
