### ISSUE TITLE
How do I make it convert 20971520 to 20M?

### ISSUE THREAD

**Issue by meglio** [avoidwork/filesize.js#140]
I can't figure out, how do I convert 20 x 1024 x 1024 = 20971520 to 20M?
Whatever options I try, it is never `20M`.

**Comment by avoidwork** [comment]
@meglio 8.0.0 changed the default base to 10, so in your case specify `base: 2`, or use 7.0.0.

**Comment by Hypnosphi** [comment]
@avoidwork did you actually try it?

```
> filesize(20971520, {base: 2})
'20 MiB'
```

**Comment by meglio** [comment]
@avoidwork , please check - it outputs 21M, not 20M

<img width="376" alt="image" src="https://user-images.githubusercontent.com/282177/133782582-6baf0e67-aeee-41c4-8718-bded00d323d8.png">

**Comment by avoidwork** [comment]
please open a pr, you make the change you want to see. 🤷🏻‍♂️ 

![Screenshot 2021-09-17 085843](https://user-images.githubusercontent.com/369698/133786364-bb5a09b8-662f-4eca-a05e-6fccd5ebf59b.png)

**Comment by meglio** [comment]
What do you mean "the change I want to see"?

I'm basically reporting the issue with the website - it shows 21M instead of 20M despite me selecting "Unix mode". Is this expected? It seems like a bug in the website.

**Comment by avoidwork** [comment]
cool.

**Comment by meglio** [comment]
So could you fix the website please? It's a bit confusing when it renders something that's not expected as by the documentation.

**Comment by avoidwork** [comment]
why can't you fix the website?

**Comment by meglio** [comment]
Because I have not been contributing to this package as a coder and have no intention to do so. My contribution in this case is a detailed report of an issue and the time spent on explaining it here in Github Issues.

**Comment by avoidwork** [comment]
cool, i'll just roll it back then.

**Comment by avoidwork** [comment]
you just talked your fix out of existance. good luck with your contribution method in the future.

**Comment by meglio** [comment]
The only consequence of such an "educational" rollback is that I'll have to switch to another library, put yours in the "Avoid, toxic maintainer" list, and stop my contributions here as a tester who cared to put his time into reporting real issues. Thanks.

**Comment by bruceCzK** [comment]
It's definitely not the expected result. I can't think out a reason why to change the default setting.
