### ISSUE TITLE
base: 10 uses mibibytes

### ISSUE THREAD

**Issue by Hypnosphi** [avoidwork/filesize.js#141]
```
> filesize(1e6)
'1 MiB'
```

It should be megabytes instead

**Comment by avoidwork** [comment]
for less than a day a week ago; introduced the bug while fixing another bug and then reverted the following day.

**Comment by avoidwork** [comment]
https://github.com/avoidwork/filesize.js/commit/afd78c28524d7a9e4830769385d2ade467991d90
