### ISSUE TITLE
BigInt support?

### ISSUE THREAD

**Issue by danielberndt** [avoidwork/filesize.js#146]
Passing a [BigInt](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt) to filesize causes an exception (in Chrome 98, but it's probably the same in all other envs too):

> Uncaught TypeError: Cannot convert a BigInt value to a number
>    at isNaN (<anonymous>)

Given that BigInt is [widely supported](https://caniuse.com/bigint) these days it could make sense for this library to also support it as an input.

Curious about your thoughts!

**Comment by avoidwork** [comment]
sounds good to me.

**Comment by avoidwork** [comment]
This is 10.0.0.
