### ISSUE TITLE
Standard property does not switch base

### ISSUE THREAD

**Issue by zerkms** [avoidwork/filesize.js#152]
```js
console.log(filesize(265318, {standard: "jedec"}), filesize(265318, {standard: "iec"})) // 265.32 KB 265.32 KiB
```

Related: https://github.com/avoidwork/filesize.js/issues/148

**Comment by avoidwork** [comment]
This is a regression and undone with 9.0.8. the standards do not dictate the base, because they are both base 2. The decimal prefix delta of JEDEC is only the lower case 'k' on kilo.

**Comment by avoidwork** [comment]
To clarify: the base does dictate the standard; base 10 is JEDEC (unless overridden) with a tiny string op for the 'k' as per 2.x.x - 8.x.x.

I restructured the conditional statements to make it clearer:

```javascript
	// Sync base & standard
	if (base === -1 && standard.length === 0) {
		base = 10;
		standard = JEDEC;
	} else if (base === -1 && standard.length > 0) {
		standard = standard === IEC ? IEC : JEDEC;
		base = standard === IEC ? 2 : 10;
	} else {
		base = base === 2 ? 2 : 10;
		standard = base === 10 ? JEDEC : IEC;
	}
```
