### ISSUE TITLE
filesize(1024); does not give "1.02 kB"

### ISSUE THREAD

**Issue by rolandstarke** [avoidwork/filesize.js#154]
The Readme has an example of:

```node
filesize(1024);                       // "1.02 kB"
```

But the actual output is:
```node
filesize(1024);                       // "1.02 kiB"
```

Would be cool if it worked like in the Readme. 
Also see: https://github.com/avoidwork/filesize.js/issues/150

For Anyone else you can use v8.0.7
```html
<script src="https://unpkg.com/filesize@8.0.7/lib/filesize.min.js" defer></script>
```

**Comment by rolandstarke** [comment]
See: https://github.com/avoidwork/filesize.js/issues/150

The i indicates base 2. So changing the default to base 10 should also remove the i.

**Comment by avoidwork** [comment]
It does work like the README.md says, the first option (base) has a default of 10. I've removed the outdated examples to remove confusion.

**Comment by rolandstarke** [comment]
I am looking for using the SI prefix for base 10.


See https://wiki.ubuntu.com/UnitsPolicy
Or https://en.m.wikipedia.org/wiki/Byte#Multiple-byte_units


But it's ok. I will use the v8.0.7 version.

**Comment by avoidwork** [comment]
totally agree. 9.0.0 shifted it because https://github.com/avoidwork/filesize.js/issues/152 is the cause of the regression.

there's 2 camps which do not agree on how it works. I'll return the original behavior and 9 is burned as a bad version.

**Comment by avoidwork** [comment]
This is 9.0.9.
