### ISSUE TITLE
filesize(1024, { base: 2, standard: 'jedec' }) does not return 1 KB 

### ISSUE THREAD

**Issue by mil7** [avoidwork/filesize.js#156]
Hi there,

since the update to **v9.0.9** the legacy notation to base 2 does not work anymore. Instead

```
filesize(1024, { base: 2, standard: 'jedec' }) === filesize(1024, { base: 2, standard: 'iec' }) === 1 KiB
```

**v9.0.8** worked. The regression https://github.com/avoidwork/filesize.js/pull/155 removes all "jedec" relating tests though. I believe that was more housekeeping than intended.

**Comment by avoidwork** [comment]
9.0.9 returned all of the tests from 8.0.0 branch

**Comment by avoidwork** [comment]
The previous tests barely covered the opposite case, so that was a big mistake.
