### ISSUE TITLE
Incorrect commit links in changelog

### ISSUE THREAD

**Issue by FarSeeing** [avoidwork/filesize.js#157]
The links to commits in changelog are broken (links to issues are fine).
For example, taking one from 9.0.9,
> Fixing unit assignment (WIP) [70bb6a1](https://github.com//avoidwork/filesize.js.git/commit/70bb6a1e181919a7a2db833d194bf7ca14864cc3)

Incorrect (current) link:
`https://github.com//avoidwork/filesize.js.git/commit/70bb6a1e181919a7a2db833d194bf7ca14864cc3`
Correct (`.git` part is missing):
`https://github.com//avoidwork/filesize.js/commit/70bb6a1e181919a7a2db833d194bf7ca14864cc3`

Haven't investigated deeply but it seems because of the repository URL in `package.json`

**Comment by avoidwork** [comment]
You're welcome to fix npm bugs.

**Comment by avoidwork** [comment]
Fixed with [3b40756](https://github.com/avoidwork/filesize.js/commit/3b407564d14ab237a0287303ae2111d131d328eb); it was the URL from the webstorm ide at that time.
