### ISSUE TITLE
Node 14 incompatible?

### ISSUE THREAD

**Issue by ryanb** [avoidwork/filesize.js#161]
I'm getting this error when attempting to install the latest 10.0.0 update on Node 14.

```
error filesize@10.0.0: The engine "node" is incompatible with this module. Expected version ">= 16.0.0". Got "14.20.1"
```

Is this package intentionally no longer compatible with Node 14? This seems like a significant change, and I didn't see mention of it in the changelog.

If this is intentional, perhaps add it to the changelog and the readme.

Either way, thanks for your work on this!

**Comment by avoidwork** [comment]
No real reason beyond current LTS; i'll drop it to 14.

**Comment by avoidwork** [comment]
This is 10.0.1.

**Comment by avoidwork** [comment]
The change came in with "Building with revision dependencies" which is in the CHANGELOG.md file. I don't write multiple sentences for commits usually.

https://github.com/avoidwork/filesize.js/commit/00ff1aea8d56d0f184a7fd0226506428a9edb3dc which you can see at https://github.com/avoidwork/filesize.js/blob/master/CHANGELOG.md#1000
