### ISSUE TITLE
CDN is down

### ISSUE THREAD

**Issue by dniccum** [avoidwork/filesize.js#165]
Hey guys, just a heads up, the cdn-hosted production build is throwing a 404. These are the links that I am referring to:

* https://cdn.filesizejs.com/filesize.min.js
* https://cdn.filesizejs.com/filesize.js

**Comment by avoidwork** [comment]
thats just a forward to another project that pulls from github.

**Comment by avoidwork** [comment]
Issue is with https://github.com/cdnjs/cdnjs
