### ISSUE TITLE
Not compatible with Node.js v12?

### ISSUE THREAD

**Issue by medikoo** [avoidwork/filesize.js#168]
Recently following the [CHANGELOG](https://github.com/avoidwork/filesize.js/blob/master/CHANGELOG.md), I've upgraded `filesize` from v8 to v10. 

There are no notes in CHANGELOG that support for Node.js v12 was dropped. Yet suddenly, I got [a report from a user](https://github.com/serverless/serverless/issues/11594) stating that you log a warning that Node.js v12 is not supported. Is that the case?

If it's the case, can you indicate that in the CHANGELOG file to avoid further confusion (?) Otherwise, can you update the warning notice so it doesn't scream at Node.js v12 users

**Comment by medikoo** [comment]
@avoidwork npm emits that message based on metadata in package.json. Also, you've already fixed that once: https://github.com/avoidwork/filesize.js/issues/161 :)

**Comment by avoidwork** [comment]
@medikoo this is fixed with 10.0.6, such that 10.4.0 is the minimum version.

Regarding min version... I moved it from 0.4.0 to current stable after 11 years, it's interesting to see what products are using what versions due to RTE, etc..
