### ISSUE TITLE
Unable to override custom symbols translations

### ISSUE THREAD

**Issue by gurpreetbaidwan** [avoidwork/filesize.js#176]
Unable to override symbols using custom translation text. I couldn't find any examples to do so based on the new definition of symbols object. This is the best I could think of. 
   
   ```
const symbols = {
            iec: { bits: [], bytes: [] },
            jedec: {
                bits: [],
                bytes: [
                     "bytes",
                     "KB",
                     "MB",
                     "GB",
                ]
            }
        };
const size = partial({ symbols: symbols, base: 2, standard: "jedec" });
return size(value || 0);
```

**Comment by avoidwork** [comment]
Hi, I merged your PR assuming you ran the tests, but most tests failed, so it was force-pushed out. I'm adding husky to enforce pre-commit actions.

```console
> filesize@10.1.0 mocha
> mocha test/*.js



  Testing functionality
    1) It should pass base2 tests
    2) It should pass base2 JEDEC tests
    3) It should pass base10 tests
    4) It should pass base10 IEC tests
    √ It should pass invalid input tests
    5) It should pass symbols tests
    6) It should pass partial() tests
    7) It should pass bits tests
    8) It should pass full forms tests
    9) It should pass exponent tests
    10) It should pass separator tests
    11) It should pass locale tests
    12) It should pass localeOptions tests
    13) It should pass roundingMethod tests
    14) It should pass precision tests
    15) It should pass defaults tests
    16) It should pass BigInt tests


  1 passing (11ms)
  16 failing

  1) Testing functionality
       It should pass base2 tests:
     TypeError: Cannot read properties of undefined (reading 'bytes')
      at filesize (file:///C:/Users/jason/Projects/filesize.js/dist/filesize.esm.js:158:31)
      at Context.<anonymous> (file:///C:/Users/jason/Projects/filesize.js/test/filesize_test.js:21:16)
      at process.processImmediate (node:internal/timers:478:21)
```

**Comment by avoidwork** [comment]
This is actually a really old feature; I removed the block of samples from the README because it was an outdated gist.

The tests are the easiest place to see how it's used:

```
it("It should pass symbols tests", function () {
	assert.equal(filesize(this.byte, {base: 10, symbols: {B: "Б"}}), "1 Б", "Should be '1 Б'");
	assert.equal(filesize(this.kibibyte, {base: 10, symbols: {B: "Б"}}), "1.02 kB", "Should be '1.02 kB'");
});
```

**Comment by avoidwork** [comment]
I've returned the gist content to the README; that file & the dist outputs need to be updated.

**Comment by avoidwork** [comment]
Closing this issue, with the intention to revisit the `README.md`.

**Comment by gurpreetbaidwan** [comment]
Hi @avoidwork 
You suggested code is exactly how I was passing symbols before but it stopped to work after the update as the symbols definition has changed. 
![image](https://github.com/avoidwork/filesize.js/assets/4227224/49686afa-61d9-434d-8711-94b3cb790b3c)

![image](https://github.com/avoidwork/filesize.js/assets/4227224/28d17c5a-23cd-4420-ab18-a87bbbf6c4c6)

I had tried my fix which was working for me unfortunately I broke something else I guess.

**Comment by gurpreetbaidwan** [comment]
Perhaps only the symbols option Type needs to be fixed and code would work as expected as per your example.

**Comment by gurpreetbaidwan** [comment]
#177

**Comment by avoidwork** [comment]
@tschlechtweg, as the PR author who introduced the definition, is this looser version going to cause an issue?

**Comment by tschlechtweg** [comment]
@avoidwork It will not cause an issue with the return type infering, such that I do not have arguments against it.

**Comment by gurpreetbaidwan** [comment]
Thank you @avoidwork  & @tschlechtweg 
:)
