### ISSUE TITLE
Demo not working on https://filesizejs.com

### ISSUE THREAD

**Issue by undsoft** [avoidwork/filesize.js#179]
1. I typed 40000 in Try it! section on https://filesizejs.com.
2. I got: 
```
filesize is not a function. (In 'filesize(val, {base: input.dataset.base10 === 'true' ? 10 : 2, bits: input.dataset.bits === 'true'})', 'filesize' is an instance of HTMLInputElement)
```

**Comment by avoidwork** [comment]
Fixed; the website is setup to work with 9.x while the repo is 10.x - just needed to checkout a tag on the new webserver.
