### ISSUE TITLE
1023 B != 1 kB

### ISSUE THREAD

**Issue by binarykitchen** [avoidwork/filesize.js#59]
When I do 

```js
filesize(1023, {
    round: 0
})
```

it returns `1 kB` but I expect `1023 B` ... is this a bug or am I missing an option?

**Comment by avoidwork** [comment]
Bug, I'll see what's up.

**Comment by binarykitchen** [comment]
good boy ;)

**Comment by avoidwork** [comment]
Sorry about that; just pushed to npm.

**Comment by binarykitchen** [comment]
no need to be sorry, bugs are a very normal part in a hacker's life heh
