### ISSUE TITLE
It would be nice to have a https a link to a cdn

### ISSUE THREAD

**Issue by NameFILIP** [avoidwork/filesize.js#61]
> 2014.12.17: Now that SSL is encouraged for everyone and doesn’t have performance concerns, this technique is now an anti-pattern. If the asset you need is available on SSL, then always use the https:// asset.
> 
> -- <cite>[Paul Irish](http://www.paulirish.com/2010/the-protocol-relative-url)</cite>

The library is cool, but I had issues using it over the https. I've ended up using [rawgit](https://rawgit.com/faq): https://cdn.rawgit.com/avoidwork/filesize.js/3.1.2/lib/filesize.js

It would be nice to have a https link to the lib in the documentation

**Comment by avoidwork** [comment]
Hi,

So I'm operating the `cdn.filesizejs.com` out of pocket, at a loss. So, if you provide the cert, I'll configure the cdn to use it. I'm using www.cdn77.com.

**Comment by NameFILIP** [comment]
Is there a need for it at all? Are there any advantages comparing to rawgit?

**Comment by NameFILIP** [comment]
It's an open-source library, there should be a way to host it on some cdn for free.. don't you think?

**Comment by avoidwork** [comment]
Well, here's the thing... it being on a CDN controlled by me is the result of someone opening an issue years ago, so consider this the second ping on the subject. It doesn't impact me day to day, so I don't care either way. If rawgit can work with CNAMEs, then I'm happy to point at their system.

**Comment by avoidwork** [comment]
For context, I won't openly endorse a product I'm not a part of. In the past I've done this in READMEs and I always feel dirty afterwards, as there's no benefit.

**Comment by NameFILIP** [comment]
What do you mean by "can work with CNAMEs"?

I don't really care if it's rawgit or some other cdn. But not having https support is an issue in 2015.

**Comment by avoidwork** [comment]
Why is it my issue? I'm not responsible for providing you with an https connection. I'm providing a CDN, if you want SSL i'll add it if you pay for it.

**Comment by NameFILIP** [comment]
Why should I pay for it if there is a way to do it for free?

**Comment by avoidwork** [comment]
What are you asking for exactly? If you want SSL on the CDN, that would be _my_ CDN, and since I don't care, you can pay for the cert and I'll set it up. If you mean in general, I really don't care 'cause this lib is all over the net... on places like softpedia.com ... literally, everywhere; not my responsibility.

**Comment by NameFILIP** [comment]
The question is: why do you need your own CDN instead of using one of the top popular CDNs?
One of the arguments - you can get the SSL support for free.

https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=cdn+javascript

**Comment by avoidwork** [comment]
This is why https://github.com/avoidwork/filesize.js/issues/2 ... 3 years ago there was less "free" and more "hey, that would be useful". Considering how it's available, it's really not an issue to solve. You could add it to any CDN you want, but if you need it wired with hooks, then just tell me where to add it.

**Comment by avoidwork** [comment]
https://wzrd.in/standalone/filesize@latest
