### ISSUE TITLE
Add localization addons

### ISSUE THREAD

**Issue by Grawl** [avoidwork/filesize.js#64]
I suggest to create right-crafted localization javascript files to choose from (or better detect automatically), something like `filesize.ru.js` with following content:

```js
{
    "B": "Б",
    "kB": "кБ",
    "MB": "МБ",
    "GB": "ГБ",
    "TB": "ТБ",
    "PB": "ПБ",
    "EB": "ЭБ",
    "ZB": "ЗБ",
    "YB": "ЙБ"
}
```

...but with right context.

And call to PR new languages.

**Comment by avoidwork** [comment]
I've often considered the gap in the API design around this particular issue, it's not curry friendly. I think this could be solved with a facade.

How would you use this? Would you detect the locale & load one of many files? Can we extend the current lib to make this configuration easier?

**Comment by avoidwork** [comment]
The obvious/simple & breaking change is to reverse the arguments so you can curry the config.

**Comment by avoidwork** [comment]
Closing due to lack of input, and the fact that you can do this with the config descriptor today.
