### ISSUE TITLE
Correctly check for AMD loader

### ISSUE THREAD

**Issue by boris-petrov** [avoidwork/filesize.js#65]
You are currently doing:

```javascript
if (typeof define === 'function')
```

While it should be:

```javascript
if (typeof define === 'function' && define.amd)
```

Otherwise it breaks, e.g. in Ember.js.

**Comment by avoidwork** [comment]
Pull request welcome! I don't use ember or care about it.

**Comment by boris-petrov** [comment]
Should I commit also the grunt-updated files (the stuff in `lib`) or just the change in `src`?

**Comment by avoidwork** [comment]
It should be everything. Make your change to `src` file, build, if tests pass please commit the result. People that clone shouldn't have to 'build' to get your change, imo.
