### ISSUE TITLE
Incorrect bit abbreviation in one case

### ISSUE THREAD

**Issue by tom-weatherhead** [avoidwork/filesize.js#68]
In src/intro.js, the line:

bits: [ "B", "kb", "Mb", ... ],

... should be:

bits: [ "b", "kb", "Mb", ... ],

This way, one bit will be described as "1 b" and not "1 B", which looks like one byte.

**Comment by avoidwork** [comment]
Hi,

Thanks for noticing! This is a mistake based on [IEEE 1541](https://en.wikipedia.org/wiki/IEEE_1541-2002).
