### ISSUE TITLE
is it a mistake? "kB"

### ISSUE THREAD

**Issue by bhuranideepak82** [avoidwork/filesize.js#69]
I see MB,GB etc....all in capital

but kb is kB (k small)

**Comment by avoidwork** [comment]
It's not a mistake: https://en.wikipedia.org/wiki/Kilobyte

**Comment by avoidwork** [comment]
Well, I guess it could be a mistake if you're expecting JEDEC. It's easy to change if you feel that should be what's used; I don't really have an opinion.
