### ISSUE TITLE
Intro.js code broken

### ISSUE THREAD

**Issue by Pavel910** [avoidwork/filesize.js#70]
The `intro.js` code is broken - missing `});` at the end of file.

```
(function (global) {
const b = /^(b|B)$/;
const si = {
	bits: ["b", "kb", "Mb", "Gb", "Tb", "Pb", "Eb", "Zb", "Yb"],
	bytes: ["B", "kB", "MB", "GB", "TB", "PB", "EB", "ZB", "YB"]
};
```

**Comment by Pavel910** [comment]
Just realized you are joining 3 files into the final build. I don't understand why it didn;t work after gulp build since you are pointing to correct main file in bower.json. Forget this issue. Cheers.

**Comment by avoidwork** [comment]
Is there a way to recreate this issue? It may be the path of the lib, but I'm not sure since I don't use bower.

**Comment by Pavel910** [comment]
Everything works, I guess it was a problem in my gulp and bower files parsing. Sorry for bothering you :)

**Comment by avoidwork** [comment]
:+1: np
