### ISSUE TITLE
Inconsistency in tests and examples

### ISSUE THREAD

**Issue by starius** [avoidwork/filesize.js#72]
https://github.com/avoidwork/filesize.js/blob/f7a059f/test/filesize_test.js#L22
```javascript
this.kilobit = 500;
// ...
test.equal(filesize(this.kilobit, {bits :true}), "3.91 Kb", "Should be '3.91 Kb'");
```

https://github.com/avoidwork/filesize.js/blob/f7a059f/README.md
```javascript
filesize(500, {bits: true});          // "4 kb"
```

Discrepancies:
  * k / K
  * 4 / 3.91

See also #69

**Comment by avoidwork** [comment]
You're welcome to change it with a PR.

**Comment by avoidwork** [comment]
The website is also 2-3yr out of date, please include updates there too.

**Comment by starius** [comment]
Ok, I'll change values in examples to what is actually returned.

**Comment by starius** [comment]
> The website is also 2-3yr out of date, please include updates there too.

The example on the site is loaded with gist https://gist.github.com/4698968.js
I can't make a pull request to gist.

**Comment by starius** [comment]
I'm trying to reimplement it in Lua: https://github.com/starius/lua-filesize 
I've used the example as the first test.

**Comment by avoidwork** [comment]
Ah, well I guess that's unfortunate timing; all of the tests were corrected for JEDEC/SI, because it used to be SI centric.
