### ISSUE TITLE
option "skip" is not documented

### ISSUE THREAD

**Issue by starius** [avoidwork/filesize.js#73]

**Comment by avoidwork** [comment]
That's because it's clearly deprecated; it's always `false`. It should be erased.

**Comment by starius** [comment]
> it's clearly deprecated

It is not clear, because it is not covered by the documentation. Can you erase it, please?

**Comment by avoidwork** [comment]
Yup, either tomorrow or on the weekend.

**Comment by avoidwork** [comment]
> It is not clear, because it is not covered by the documentation

Documentation and deprecated code are not related. It's an internal variable, so there's no reason it _would_ be documented.

**Comment by starius** [comment]
I see. I thought it could be changed by the function's arguments.
