### ISSUE TITLE
It does not work properly for some extreme cases

### ISSUE THREAD

**Issue by nskazki** [avoidwork/filesize.js#77]
version: `filesize@3.2.0`

```
> filesize(1/8, { bits: true })
'1024 '
> filesize(1024*1024*1024*1024*1024*1024*1024*1024*1024, { bits: true })
'8 '
> filesize(1, { bits: true })
'8 b'
> filesize(1024*1024*1024*1024*1024*1024*1024*1024, { bits: true })
'8 Yb'
> 
```

**Comment by nskazki** [comment]
```
> filesize(1/8)
'128 '
> filesize(1)
'1 B'
> 
```

**Comment by avoidwork** [comment]
Hi,

Good catch! This looks like a regression from a reduction in complexity that happened awhile ago. The `e` value gets turned into a `9` and no longer maps to a symbol.

<img width="998" alt="screen shot 2016-01-29 at 5 14 22 pm" src="https://cloud.githubusercontent.com/assets/369698/12689588/df56add6-c6ab-11e5-80d3-41406aeb7acf.png">
