### ISSUE TITLE
Can I set a locale for "Kb", "Gb" and so on?

### ISSUE THREAD

**Issue by pashinin** [avoidwork/filesize.js#81]
Looks like there is no support for multiple languages.
Maybe it's good to have one?

**Comment by avoidwork** [comment]
Are you trying to get bit sizes? if so use `base: 2` config.

If you want to use a custom language, use `symbols`.

**Comment by avoidwork** [comment]
```javascript
filesize(500);                        // "500 B"
filesize(500, {bits: true});          // "4 Kb"
filesize(265318, {base: 10});         // "265.32 kB"
filesize(265318);                     // "259.1 KB"
filesize(265318, {round: 0});         // "259 KB"
filesize(265318, {output: "array"});  // [259.1, "KB"]
filesize(265318, {output: "object"}); // {value: 259.1, suffix: "KB", symbol: "KB"}
filesize(1, {symbols: {B: "Б"}});    // "1 Б"
filesize(1024);                       // "1 KB"
filesize(1024, {exponent: 0});        // "1024 B"
filesize(1024, {output: "exponent"}); // 1
filesize(265318, {standard: "iec"});  // "259.1 KiB"
```

**Comment by Spone** [comment]
Here is what you can do for French symbols for instance:

```js
filesize(1024, { symbols: { B: "o", KB: "Ko", MB: "Mo", GB: "Go", TB: "To", PB: "Po", EB: "Eo", ZB: "Zo", YB: "Yo" } });
```

**Comment by VityaSchel** [comment]
> Here is what you can do for French symbols for instance:
> 
> ```js
> filesize(1024, { symbols: { B: "o", KB: "Ko", MB: "Mo", GB: "Go", TB: "To", PB: "Po", EB: "Eo", ZB: "Zo", YB: "Yo" } });
> ```

Same but for Russian language:

```javascript
filesize(1024, { symbols: { B: 'Б', kB: 'кБ', MB: 'МБ', GB: 'ГБ', TB: 'ТБ', PB: 'ПБ', EB: 'ЭБ', ZB: 'ЗБ', YB: 'ЙБ' } })
```

**Comment by jbuiquan** [comment]
> Here is what you can do for French symbols for instance:
> 
> ```js
> filesize(1024, { symbols: { B: "o", KB: "Ko", MB: "Mo", GB: "Go", TB: "To", PB: "Po", EB: "Eo", ZB: "Zo", YB: "Yo" } });
> ```

In the version ` "filesize": "^10.1.2"`, I found that the correct case for "KB" is "kB" as in @VityaSchel response.
