### ISSUE TITLE
Certificate for filesizejs.com and cdn.filesizejs.com has expired

### ISSUE THREAD

**Issue by sisve** [avoidwork/filesize.js#82]
The certificate for filesizejs.com and cdn.filesizejs.com expired on 26 November.

Steps to reproduce:
1) Go to https://cdn.filesizejs.com/filesize.min.js
2) Gasp at the browser-implemented security screen informing you about all the hackers that "might be trying to steal your information" (Chrome).

**Comment by avoidwork** [comment]
ok, i'll take care of it. it is scary.

**Comment by avoidwork** [comment]
Updated the certs.
