### ISSUE TITLE
Uncaught Error: Cannot find module '/node_modules/filesize/lib/filesize'

### ISSUE THREAD

**Issue by binarykitchen** [avoidwork/filesize.js#87]
Looks like with the recent version bump v3.5.8 filesize is breaking my local branch for the videomail app. 

Does not happen when I revert back to the previous version. Using browserify here to require it. Can you look at this?

**Comment by evoyy** [comment]
Same issue with webpack (v1), unable to compile v3.5.8.

**Comment by avoidwork** [comment]
Don't use 3.5.8 or webpack? it's a loader script for node.js.

**Comment by avoidwork** [comment]
I'm kinda surprised webpack can't deal with that.

**Comment by avoidwork** [comment]
@binarykitchen @evoyy this is a webpack bug. feel free to link them. unit tests base when this thing compiles; not my concern. i don't use overly complex toolchains, so I have no skin in this game.
