### ISSUE TITLE
"use strict" out of function started to be global after compression

### ISSUE THREAD

**Issue by ivmakk** [avoidwork/filesize.js#88]
After using of the package in compression job (joining list of files to single assert, like UglifyJS) "use strickt" will be placed in global scope.

For providing isolation of libraries scope better to move "use strict" usage into function's block:
```
(function (global) {
    "use strict";
    // code... 
})(typeof window !== "undefined" ? window : global);
```

**Comment by avoidwork** [comment]
That's the result of https://github.com/mishoo/UglifyJS so you can open a bug there.

**Comment by avoidwork** [comment]
btw, technically there's no difference as it's packaged by the build task. 'use strict' is scoped to the script which is correct. repackaging the lib is not my concern.

**Comment by avoidwork** [comment]
You would also want to file a bug with https://github.com/babel/babili for the minified es6 file.
