### ISSUE TITLE
Certificates for filesizejs.com and cdn.filesizejs.com have expired

### ISSUE THREAD

**Issue by puffrfish** [avoidwork/filesize.js#89]
Hello,

The certificates for both filesizejs.com and cdn.filesizejs.com have expired. Looks like they need to be renewed with the letsencrypt client being used.

![screen shot 2017-08-11 at 10 40 43 pm](https://user-images.githubusercontent.com/3316865/29237168-62cc1982-7ee6-11e7-9439-30a02f709690.png)

**Comment by avoidwork** [comment]
i'll fix the certs this week; that's not an actual cdn hostname. it used to be used to front one, but hasn't been an actual cdn entry point for a long time; it's a single server in new york city, so I wouldn't rely on it.

someone added filesize to a cdn recently; I think maxcdn? one of the more popular js lib friendly ones.

**Comment by avoidwork** [comment]
Resolved; new server with certbot renew on crontab.
