### ISSUE TITLE
Website and CDN gone and Cloudflare error page is shown

### ISSUE THREAD

**Issue by kaspergrubbe** [avoidwork/filesize.js#92]
Hi, it seems like https is working, but that Cloudflare can't reach the backend.

**Comment by kaspergrubbe** [comment]
In the meantime I guess people can use cdnjs for a mirror:

https://cdnjs.com/libraries/filesize (Instead of `http://cdn.filesizejs.com/filesize.min.js` (like I did))

It is even versioned! 👍

**Comment by avoidwork** [comment]
cdnjs.com is the only thing that should be used; i'll be changing the webpage links to it later today. site is back up.

**Comment by kaspergrubbe** [comment]
Thank you, I was a bit afraid that it was too much to ask for (given your github username ;)).

**Comment by avoidwork** [comment]
oh, no... it's the reverse! i setup a cdn years ago for 1 person and then it stuck around for a few years, and now it's dead.... cause that other cdn ;)

**Comment by avoidwork** [comment]
i've put the old `cdn.filesizejs.com` domain up, but please use cdnjs instead.
