### ISSUE TITLE
Question: Support localize converting ?

### ISSUE THREAD

**Issue by AhnpGit** [avoidwork/filesize.js#93]
Hi,

I checked the document of filesize.js about converting to localized number but I couldn't find any options. Does filesize.js support converting to localized number ? For example in UK they use `dot` as decimal separator while some other countries they use `comma`

**Comment by avoidwork** [comment]
Hi,

At this time it does not. If I were to add that, it would probably just be specifying a delimiter (default would be ""). How does that sound?

**Comment by avoidwork** [comment]
Follow up question, if your formatting with a period, how do you know what's the decimal place?

**Comment by AhnpGit** [comment]
Hi,
I think providing an option to specify the delimiter sounds good. What I have in mind is after your library finishes the part of calculating the number, taking the option delimiter which the user passes in and use it to replace your `comma`. What do you think ? I don't know if the calculation needs to take into account of thousand separator as well or not

**Comment by avoidwork** [comment]
oic, i misunderstood; shouldn't be a problem landing this.

**Comment by AhnpGit** [comment]
Perhaps providing an optional thousand separator and also an optional decimal separator look better for me :) We don't know who wants to have thousand separator in their codes even though I don't see that case that often
