### ISSUE TITLE
Expose ES6 build in npm

### ISSUE THREAD

**Issue by boris-petrov** [avoidwork/filesize.js#94]
Thanks for the library! We've been using the ES6 file from the bower distribution, but now have switched to the NPM one where only an ES5 file is available. Perhaps you could also include the ES6 one?

**Comment by avoidwork** [comment]
hi, I tried but it turns out bundlers like webpack assume much and mess with a facade that can load es5 or es6+ code 👎 ... see https://github.com/avoidwork/filesize.js/issues/87

it has to be more like an extinction, aka 4.0.0 will only be es6+

**Comment by boris-petrov** [comment]
I see. But having an ES6 only build would break, e.g., Ember's build system. When you add something to the "vendor" file there, it doesn't get processed in any way - so when we want to build an ES5 build (for older browsers) we **have** to use **only** ES5 files. So that would break this usecase.

Could you not have different directories or something for the different builds?

**Comment by avoidwork** [comment]
Bumping the 'major' implies a breaking change, and taking away a transpile is a breaking change for older RTEs, so I think this is correct.

**Comment by avoidwork** [comment]
> Could you not have different directories or something for the different builds?

that's effectively what I had with #87 ... the bundlers do not consider a dynamic load, so what they see at run time is what they spit out.

**Comment by avoidwork** [comment]
3.6.1 includes the es6 version, which you can load via file path.
