### ISSUE TITLE
Changelog for the major update

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [avoidwork/filesize.js#95]
I just noticed that the library has had a major update. Has there been any breaking changes? A changelog would be nice so that I can determine the changes required on my end.

**Comment by avoidwork** [comment]
What changed was the deprecated 'suffixes' option was removed after a year+ of having that status; see https://github.com/avoidwork/filesize.js/commit/a0b268f8b127cfc9327de53a489aad2b2a01dcb1

**Comment by SayakMukhopadhyay** [comment]
Thanks for the info. Appreciate it!

**Comment by Hypnosphi** [comment]
Same question for 5.0

**Comment by avoidwork** [comment]
@Hypnosphi if you can post this comment, you can look at the commit log just under "Issues" in the main repo view. I'm not going to spend my time on stuff when the commit total is under 500, because ... this repo is 8 years old with under 150 commits... you can _easily_ determine the difference.

**Comment by avoidwork** [comment]
to expand on this... _if_ you _really_ want the changelog, open the PR with the code that'll generate it; you want it, not me, and you can land that feature anytime you want to create it.

**Comment by Hypnosphi** [comment]
One thing that I didn't find out looking at the commits is the fact that starting from 5.0, you have to transpile `filesize` library with babel if you need IE 11 support.

**Comment by avoidwork** [comment]
Correct; I don't support IE11 in my work or play. It's time has passed.

**Comment by avoidwork** [comment]
i can make the absent 4.x branches if that'd help with a maintenance concern

**Comment by dmison** [comment]
> One thing that I didn't find out looking at the commits is the fact that starting from 5.0, you have to transpile `filesize` library with babel if you need IE 11 support.

Don't suppose you have any pointers/reference/example for this?  I tried specifying `node_modules/filesize` in webpack config for babel-loader to no avail.

**Comment by Hypnosphi** [comment]
@dmison how exaxctly did you try to do this? In my case, it's a separate `babel-loader` rule with `{modules: 'commonjs'}`:
```js
{
  test: /\.js$/,
  include: /node_modules\/filesize\//,
  use: [
    {
      loader: 'babel-loader',
      options: {
        cacheDirectory: true,
        babelrc: false,
        presets: [
          [
            '@babel/preset-env',
            {
              modules: 'commonjs',
            },
          ],
        ],
      },
    },
  ],
}
```

**Comment by dmison** [comment]
I just added the include line to our existing babel-loader config.  Didn't even occur to me to add another rule.  And didn't specify any options either.  Will experiment with this when I get into work.  Thank you so much for the example.  ❤️
