### ISSUE TITLE
Add changelog

### ISSUE THREAD

**Issue by Ky6uk** [avoidwork/filesize.js#97]
I have noticed library has been updated from `v4.0.0` to `v4.1.1` but I can't find changelog for that. It could be nice to write some strings about changes (different file or maybe inside github releases page). 

Right now it's a little bit hard to maintain [TS definitions](https://www.npmjs.com/package/@types/filesize) for this library when you don't know about changes.

**Comment by avoidwork** [comment]
https://help.github.com/articles/comparing-commits-across-time/

https://github.com/avoidwork/filesize.js/compare/4.0.0...4.1.1

I forgot to tag & push 4.1.0, so I'll do that now

**Comment by Hypnosphi** [comment]
Comparing tags is good, but I'd like to know which of the commits are breaking changes

**Comment by avoidwork** [comment]
https://github.com/avoidwork/filesize.js/compare/4.2.0...5.0.0

there's not a single commit with a breaking change consistently, because i don't care to squash commits as there's value in being able to cherry pick aspects of a change (if possible / when needed).

a changelog is equal to looking at the commit history, so why do you want to dupe the information outside like that?

**Comment by Ky6uk** [comment]
> why do you want to dupe the information outside like that?

Because of a list with short notice about changes is a more convenient and familiar way of getting information about main changes than reading commits history and digging a code inside? 😐

**Comment by Hypnosphi** [comment]
@Ky6uk he clearly stated, that he doesn't care about your convenience: https://github.com/avoidwork/filesize.js/issues/95#issuecomment-537302166

**Comment by Ky6uk** [comment]
Ahh, nvm then.

**Comment by avoidwork** [comment]
@Hypnosphi you're right, i don't care about your convenience or @Ky6uk, because you're not paying for my time. I give this freely, and if you want to see something amended to it, use that passion to achieve what you want.

**Comment by avoidwork** [comment]
btw, you should always be reading the code. never trust someone else's code.
